services:
  mariadb-medical:
    container_name: mariadb-medical
    image: mariadb:latest
    ports:
      - "3306"
    volumes:
      - ./sql/doctori.sql:/docker-entrypoint-initdb.d/doctori.sql
      - ./sql/pacienti.sql:/docker-entrypoint-initdb.d/pacienti.sql
      - ./sql/programari.sql:/docker-entrypoint-initdb.d/programari.sql
    environment:
      MARIADB_USER: apidev
      MARIADB_ROOT_PASSWORD: apidev
      MARIADB_DATABASE: Medical
      TZ: Europe/Bucharest
    networks:
      - pdp_net

  mariadb-idm:
    container_name: mariadb-idm
    image: mariadb:latest
    ports:
      - "3306"
    volumes:
      - ./sql/users.sql:/docker-entrypoint-initdb.d/users.sql
    environment:
      MARIADB_ROOT_PASSWORD: idmdev
      MARIADB_USER: idmdev
      MARIADB_DATABASE: User
    networks:
      - idm_net

  mongodb-medical:
    container_name: mongodb-medical
    image: mongo:latest
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: apidev
      MONGO_INITDB_DATABASE: Medical
    networks:
      - consultations_net

  redis-idm:
    container_name: redis-idm
    image: redis:latest
    ports:
      - "6379"
    networks:
      - idm_net

  pdp:
    container_name: pdp
    image: amazoncorretto:17
    restart: on-failure
    depends_on:
      - mariadb-medical
    volumes:
      - ./PDP/target:/usr/src/app
    command: bash -c "cd /usr/src/app && java -jar PDP-1.0-SNAPSHOT.jar"
    ports:
      - "8080"
    networks:
      - pdp_net
      - gateway_net

  consult:
    container_name: consult
    image: amazoncorretto:17
    restart: on-failure
    depends_on:
      - mongodb-medical
    volumes:
      - ./consultatii/target:/usr/src/app
    command: bash -c "cd /usr/src/app && java -jar consultatii-1.0-SNAPSHOT.jar"
    ports:
      - "8080"
    networks:
      - consultations_net
      - gateway_net
    logging:
      driver: local


  idm:
    container_name: idm
    image: amazoncorretto:17
    restart: always
    depends_on:
      - mariadb-idm
      - redis-idm
    volumes:
      - ./IDM/target:/usr/src/app
    command: bash -c "cd /usr/src/app && java -jar IDM-1.0-SNAPSHOT.jar"
    ports:
      - "8080"
    networks:
      - idm_net
      - gateway_net

  gateway:
    container_name: gateway
    image: amazoncorretto:17
    restart: always
    depends_on:
      - idm
    volumes:
      - ./gateway/target:/usr/src/app
    command: bash -c "cd /usr/src/app && java -jar gateway-1.0-SNAPSHOT.jar"
    ports:
      - "8080:8080"
    networks:
      - gateway_net

networks:
  idm_net:
  pdp_net:
  consultations_net:
  gateway_net: